global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Minizon Application
  - job_name: 'minizon-app'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx metrics (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
