apiVersion: v1
kind: Service
metadata:
  name: minizon-frontend-service
  namespace: minizon
  labels:
    app: minizon-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: minizon-frontend